# Generated by Django 5.0.4 on 2026-04-11 07:31

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MiningLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_id', models.CharField(max_length=30, unique=True)),
                ('mine_name', models.CharField(max_length=200)),
                ('mineral_type', models.CharField(choices=[('COAL', 'Coal'), ('IRON_ORE', 'Iron Ore'), ('GRANITE', 'Granite'), ('LIMESTONE', 'Limestone'), ('FLUORITE', 'Fluorite'), ('DOLOMITE', 'Dolomite'), ('SAND', 'Sand'), ('OTHER', 'Other')], max_length=20)),
                ('leaseholder_name', models.CharField(max_length=300)),
                ('leaseholder_pan', models.CharField(max_length=10)),
                ('leaseholder_contact', models.CharField(max_length=15)),
                ('leaseholder_email', models.EmailField(max_length=254)),
                ('state', models.CharField(default='Telangana', max_length=50)),
                ('district', models.CharField(max_length=100)),
                ('mandal', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('survey_number', models.CharField(max_length=50)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('area_hectares', models.DecimalField(decimal_places=4, max_digits=10)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('grant_date', models.DateField()),
                ('commencement_date', models.DateField()),
                ('valid_from', models.DateField()),
                ('valid_till', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('PENDING', 'Pending'), ('SUSPENDED', 'Suspended'), ('SURRENDERED', 'Surrendered')], default='ACTIVE', max_length=20)),
                ('royalty_due', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leases_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mining Lease',
                'verbose_name_plural': 'Mining Leases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('LEASE_DEED', 'Lease Deed'), ('MINE_PLAN', 'Mine Plan'), ('SURVEY_REPORT', 'Survey Report'), ('ENV_CLEARANCE', 'Environmental Clearance'), ('COMPLIANCE_CERT', 'Compliance Certificate'), ('RENEWAL_ORDER', 'Renewal Order'), ('LEGAL_DOCUMENT', 'Legal Document'), ('ROYALTY_RECEIPT', 'Royalty Receipt'), ('INSPECTION_REPORT', 'Inspection Report'), ('OTHER', 'Other')], max_length=30)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('file_mime_type', models.CharField(default='application/pdf', max_length=100)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_till', models.DateField(blank=True, null=True)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='leases.leasedocument')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='leases.mininglease')),
            ],
            options={
                'verbose_name': 'Lease Document',
                'verbose_name_plural': 'Lease Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUAL', 'Annual')], default='MONTHLY', max_length=10)),
                ('period_year', models.PositiveSmallIntegerField()),
                ('period_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('period_quarter', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('quantity_produced_mt', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('quantity_dispatched_mt', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('quantity_stockpile_mt', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('operating_days', models.PositiveSmallIntegerField(default=0)),
                ('machinery_deployed', models.PositiveSmallIntegerField(default=0)),
                ('workforce_strength', models.PositiveSmallIntegerField(default=0)),
                ('royalty_payable', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('royalty_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('anomaly_score', models.FloatField(default=0.0)),
                ('anomaly_flags', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('FLAGGED', 'Flagged - Anomaly Detected')], default='DRAFT', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_records', to='leases.mininglease')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_production_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Production Record',
                'verbose_name_plural': 'Production Records',
                'ordering': ['-period_year', '-period_month'],
            },
        ),
        migrations.AddIndex(
            model_name='mininglease',
            index=models.Index(fields=['lease_id'], name='leases_mini_lease_i_1576b8_idx'),
        ),
        migrations.AddIndex(
            model_name='mininglease',
            index=models.Index(fields=['district'], name='leases_mini_distric_245c76_idx'),
        ),
        migrations.AddIndex(
            model_name='mininglease',
            index=models.Index(fields=['status'], name='leases_mini_status_3e4a0f_idx'),
        ),
        migrations.AddIndex(
            model_name='mininglease',
            index=models.Index(fields=['mineral_type'], name='leases_mini_mineral_3d6bb4_idx'),
        ),
        migrations.AddIndex(
            model_name='mininglease',
            index=models.Index(fields=['valid_till'], name='leases_mini_valid_t_537862_idx'),
        ),
        migrations.AddIndex(
            model_name='leasedocument',
            index=models.Index(fields=['lease', 'category'], name='leases_leas_lease_i_d64017_idx'),
        ),
        migrations.AddIndex(
            model_name='leasedocument',
            index=models.Index(fields=['is_current'], name='leases_leas_is_curr_6e8418_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productionrecord',
            unique_together={('lease', 'period_type', 'period_year', 'period_month', 'period_quarter')},
        ),
    ]
