# Generated by Django 5.0.4 on 2026-04-08 13:10

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MiningLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_id', models.CharField(max_length=30, unique=True)),
                ('mine_name', models.CharField(max_length=200)),
                ('mineral_type', models.CharField(choices=[('COAL', 'Coal'), ('IRON_ORE', 'Iron Ore'), ('GRANITE', 'Granite'), ('LIMESTONE', 'Limestone'), ('FLUORITE', 'Fluorite'), ('DOLOMITE', 'Dolomite'), ('SAND', 'Sand'), ('OTHER', 'Other')], max_length=20)),
                ('leaseholder_name', models.CharField(max_length=300)),
                ('leaseholder_pan', models.CharField(max_length=10)),
                ('leaseholder_contact', models.CharField(max_length=15)),
                ('leaseholder_email', models.EmailField(max_length=254)),
                ('state', models.CharField(default='Telangana', max_length=50)),
                ('district', models.CharField(max_length=100)),
                ('mandal', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('survey_number', models.CharField(max_length=50)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('area_hectares', models.DecimalField(decimal_places=4, max_digits=10)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('grant_date', models.DateField()),
                ('commencement_date', models.DateField()),
                ('valid_from', models.DateField()),
                ('valid_till', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('PENDING', 'Pending'), ('SUSPENDED', 'Suspended'), ('SURRENDERED', 'Surrendered')], default='ACTIVE', max_length=20)),
                ('royalty_due', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leases_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mining Lease',
                'verbose_name_plural': 'Mining Leases',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lease_id'], name='leases_mini_lease_i_1576b8_idx'), models.Index(fields=['district'], name='leases_mini_distric_245c76_idx'), models.Index(fields=['status'], name='leases_mini_status_3e4a0f_idx'), models.Index(fields=['mineral_type'], name='leases_mini_mineral_3d6bb4_idx'), models.Index(fields=['valid_till'], name='leases_mini_valid_t_537862_idx')],
            },
        ),
    ]
