# Generated by Django 5.0.4 on 2026-04-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoyaltyRateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mineral_type', models.CharField(choices=[('COAL', 'Coal'), ('IRON_ORE', 'Iron Ore'), ('GRANITE', 'Granite'), ('LIMESTONE', 'Limestone'), ('FLUORITE', 'Fluorite'), ('DOLOMITE', 'Dolomite'), ('SAND', 'Sand'), ('OTHER', 'Other')], max_length=20, unique=True)),
                ('rate_per_mt', models.DecimalField(decimal_places=2, help_text='Base Royalty INR per Metric Tonne', max_digits=10)),
                ('effective_from', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Royalty Rate Configuration',
                'verbose_name_plural': 'Royalty Rate Configurations',
            },
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='dmf_payable',
            field=models.DecimalField(decimal_places=2, default=0, help_text='10% or 30% of Royalty', max_digits=15),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='nmet_payable',
            field=models.DecimalField(decimal_places=2, default=0, help_text='2% of Royalty', max_digits=15),
        ),
    ]
