# Generated by Django 5.0.4 on 2026-04-12 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0002_royaltyrateconfig_productionrecord_dmf_payable_and_more'),
        ('vehicle_tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('purpose', models.CharField(choices=[('INSPECTION', 'Official Inspection'), ('TRANSPORT', 'Mineral Transportation'), ('SURVEY', 'DGPS/ETS Survey'), ('RECOVERY', 'Disaster Recovery')], default='TRANSPORT', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authorized_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_orders', to=settings.AUTH_USER_MODEL)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_orders', to='leases.mininglease')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_orders', to='vehicle_tracking.vehicle')),
            ],
            options={
                'verbose_name': 'Inspection Order',
                'verbose_name_plural': 'Inspection Orders',
                'indexes': [models.Index(fields=['order_id'], name='leases_insp_order_i_097a29_idx'), models.Index(fields=['start_date', 'end_date'], name='leases_insp_start_d_3bf86b_idx'), models.Index(fields=['is_active'], name='leases_insp_is_acti_8e12a7_idx')],
            },
        ),
    ]
