# Generated by Django 5.0.4 on 2026-04-11 07:31

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_name', models.CharField(blank=True, max_length=255)),
                ('user_role', models.CharField(blank=True, max_length=50)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('action_type', models.CharField(choices=[('CREATE', 'Created'), ('READ', 'Read'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EXPORT', 'Exported'), ('PRINT', 'Printed'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected')], default='READ', max_length=20)),
                ('module', models.CharField(blank=True, max_length=100)),
                ('entity_type', models.CharField(default='System', max_length=100)),
                ('entity_id', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('before_value', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('after_value', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('BLOCKED', 'Blocked')], default='SUCCESS', max_length=20)),
                ('failure_reason', models.TextField(blank=True)),
                ('previous_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('current_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='audit_audit_user_id_e8be02_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_audit_entity__9535bf_idx'), models.Index(fields=['action_type', 'timestamp'], name='audit_audit_action__74f5dd_idx'), models.Index(fields=['status'], name='audit_audit_status_dd7ae6_idx')],
            },
        ),
    ]
