# Generated by Django 5.0.4 on 2026-04-11 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('R01_SUPER_ADMIN', 'Super Admin'), ('R02_STATE_EXEC', 'State Executive'), ('R03_STATE_MGR', 'State Manager'), ('R04_DISTRICT_OFFICER', 'District Officer'), ('R05_FIELD_OFFICER', 'Field Officer'), ('R06_DATA_ENTRY', 'Data Entry Operator'), ('R07_GIS_ANALYST', 'GIS Analyst'), ('R08_AUDITOR', 'Auditor'), ('R09_LEASEHOLDER', 'Leaseholder'), ('R10_HELPDESK', 'Helpdesk'), ('R11_REPORT_VIEWER', 'Report Viewer')], default='R11_REPORT_VIEWER', max_length=30)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('designation', models.CharField(blank=True, max_length=200)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('mfa_secret', models.CharField(blank=True, max_length=32)),
                ('nic_epramaan_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
