# Generated by Django 5.0.4 on 2026-04-11 07:31

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netradyne_device_id', models.CharField(max_length=100, unique=True)),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('INSPECTION', 'Inspection Vehicle'), ('ENFORCEMENT', 'Enforcement Vehicle'), ('SURVEY', 'Survey Vehicle'), ('TRANSPORT', 'Transport/Haul Truck'), ('OFFICIAL', 'Official Vehicle')], max_length=20)),
                ('driver_name', models.CharField(max_length=200)),
                ('driver_license', models.CharField(max_length=50)),
                ('assigned_district', models.CharField(max_length=100)),
                ('last_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('current_speed_kmh', models.FloatField(default=0)),
                ('current_heading', models.FloatField(default=0)),
                ('is_online', models.BooleanField(default=False)),
                ('engine_on', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicles', to=settings.AUTH_USER_MODEL)),
                ('current_lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicles', to='leases.mininglease')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.CreateModel(
            name='VehicleAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('VA01', 'Unauthorized Mine Entry'), ('VA02', 'Geofence Entry (authorized)'), ('VA03', 'Geofence Exit'), ('VA04', 'Overspeeding'), ('VA05', 'Harsh Braking'), ('VA06', 'Harsh Acceleration'), ('VA07', 'Driver Distraction'), ('VA08', 'Driver Drowsiness'), ('VA09', 'Seatbelt Violation'), ('VA10', 'Engine Idle > 30 min'), ('VA11', 'Route Deviation'), ('VA12', 'Vehicle Offline > 2 hours'), ('VA13', 'Vehicle in eco-sensitive zone'), ('VA14', 'Speed in forest area')], max_length=30)),
                ('severity', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=10)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('timestamp', models.DateTimeField()),
                ('description', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('raw_netradyne_payload', models.JSONField(default=dict)),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_alerts', to='leases.mininglease')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='vehicle_tracking.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Alert',
                'verbose_name_plural': 'Vehicle Alerts',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VehicleLocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('speed_kmh', models.FloatField()),
                ('heading', models.FloatField()),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(default=5.0)),
                ('engine_on', models.BooleanField(default=True)),
                ('harsh_braking', models.BooleanField(default=False)),
                ('harsh_acceleration', models.BooleanField(default=False)),
                ('overspeeding', models.BooleanField(default=False)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='vehicle_tracking.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Location History',
                'verbose_name_plural': 'Vehicle Location History',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['netradyne_device_id'], name='vehicle_tra_netrady_489aa0_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['assigned_district'], name='vehicle_tra_assigne_2345e1_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['is_online'], name='vehicle_tra_is_onli_17d875_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclealert',
            index=models.Index(fields=['vehicle', 'timestamp'], name='vehicle_tra_vehicle_079158_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclealert',
            index=models.Index(fields=['severity', 'is_resolved'], name='vehicle_tra_severit_637a95_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclealert',
            index=models.Index(fields=['alert_type'], name='vehicle_tra_alert_t_36f9fa_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelocationhistory',
            index=models.Index(fields=['vehicle', 'timestamp'], name='vehicle_tra_vehicle_46e9f4_idx'),
        ),
    ]
