# Generated by Django 5.0.4 on 2026-04-09 10:51

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0001_initial'),
        ('minegis_gis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedMinePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(max_length=50, unique=True)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('approval_date', models.DateField()),
                ('valid_till', models.DateField()),
                ('approved_by', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('lease', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approved_plan', to='leases.mininglease')),
            ],
            options={
                'verbose_name': 'Approved Mine Plan',
                'verbose_name_plural': 'Approved Mine Plans',
                'ordering': ['-approval_date'],
            },
        ),
        migrations.CreateModel(
            name='ETSSurveyPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_id', models.CharField(max_length=50, unique=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('accuracy_meters', models.FloatField()),
                ('survey_date', models.DateField()),
                ('surveyor_name', models.CharField(max_length=200)),
                ('elevation', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ets_points', to='leases.mininglease')),
            ],
            options={
                'verbose_name': 'ETS Survey Point',
                'verbose_name_plural': 'ETS Survey Points',
                'ordering': ['-survey_date'],
            },
        ),
    ]
