# Generated by Django 6.1.1 on 2026-10-02 06:42

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Mandal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandals', to='mining.district')),
            ],
            options={
                'ordering': ['district__name', 'name'],
                'unique_together': {('district', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Mine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandal_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('mineral', models.CharField(blank=True, max_length=255, null=True)),
                ('mineral_type', models.CharField(blank=True, max_length=255, null=True)),
                ('survey_number', models.CharField(blank=True, max_length=255, null=True)),
                ('land_type', models.CharField(blank=True, max_length=255, null=True)),
                ('production', models.BigIntegerField(blank=True, null=True)),
                ('dispatch', models.BigIntegerField(blank=True, null=True)),
                ('ets', models.BigIntegerField(blank=True, null=True)),
                ('notice', models.BigIntegerField(blank=True, null=True)),
                ('reg_from', models.DateField(blank=True, null=True)),
                ('reg_to', models.DateField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mines', to='mining.district')),
                ('mandal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mines', to='mining.mandal')),
            ],
            options={
                'ordering': ['district__name', 'company'],
            },
        ),
    ]
